config/routes.rb
Rails.application.routes.draw do
  root 'home#upload_file'
  
  post 'home/compute_result' => "home#compute_result"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Utility
  
  def upload_file
  end

  def compute_result
    if params[:file].present?
      file_data = read_file
      # Calling Gallery Visit Calculator
      @result    = Utility::RoomVisitCalculator.new(data: file_data).call
      respond_to do |format|
        format.html
      end
    else
      redirect_to root_path, alert: "Please attach file before submitting."
    end
   
  end


  private
    def read_file
      file_params.read.split("\n")
    end

    def file_params
      params.fetch(:file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/compute_result.html.erb
<h1>Home#compute_result</h1>
<p>Find me in app/views/home/compute_result.html.erb</p>

<% @result.each do |room, results| %>
  <%= "Room #{room}, #{results[:average]} minute average visit, #{results[:visitor_count]} visitor#{results[:s]} total" %>
<%end %>

app/views/home/upload_file.html.erb
<h1>Home#upload_file</h1>
<p>Find me in app/views/home/upload_file.html.erb</p>

<%= form_tag(home_compute_result_path, multipart: true) do %>
   <div class="field">
     <%= label_tag :file %>
     <%= file_field_tag :file %>
   </div>
   <div class="actions">
      <%= submit_tag 'Submit' %>
   </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Xebia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <% if alert %>
      <p><%= alert %></p>
    <% end %>
    <% if notice %>
      <p><%= notice %></p>
    <% end %>
    <%= yield %>
  
  </body>
</html>